[package]
name = "bf_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
bf_macros = { path = "../bf-macros" }

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "bf_benchmark"
harness = false # This tells Cargo to let Criterion run the bench